version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  lint:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - run:
          name: Run lint
          command: yarn lint
  test:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - run:
          name: Run tests
          command: yarn test

workflows:
  build:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
